[build]
    build = "build"
    command = "Cl= npm run build"
    publish = "publish"

[dev]
    command = "npm run dev"
    framework = "#custom"
    targetPort = 8080
    port = 8888
    publish = "dist"
    autoLaunch = false